version: '3.8'

services:
  bot:
    build: .
    image: dam245222/app:${IMAGE_TAG}
    environment:
      ES_HOST: ${ES_HOST}
      ES_USER: ${ES_USER}
      ES_PASS: ${ES_PASS}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      DEFAULT_ADMIN: ${DEFAULT_ADMIN}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_SCHEMA: ${POSTGRES_SCHEMA}
      BOT_USERNAME: ${BOT_USERNAME}
      SPECIALIZED_TABLE: ${SPECIALIZED_TABLE}
      ES_TRANSCRIPTION_INDEX: ${ES_TRANSCRIPTION_INDEX}
    # restart: unless-stopped
    volumes:
      - /mnt/WD_RED_2TB_MIRROR/RANCZO:/app/bot/RANCZO-WIDEO:ro