name: Main Branch Production Pipeline

on:
  push:
    branches:
      - main

jobs:
  reuse-test:
    uses: ./.github/workflows/test.yml

  deploy_prod:
    runs-on: self-hosted
    needs: [reuse-test]
    steps:
      - name: Build & Push Production Image
        run: |
          docker build -t ${{ secrets.REGISTRY_URL }}/myapp:prod -t ${{ secrets.REGISTRY_URL }}/myapp:latest .
          docker push ${{ secrets.REGISTRY_URL }}/myapp:prod
          docker push ${{ secrets.REGISTRY_URL }}/myapp:latest

      - name: Deploy Production Environment
        run: docker compose -f docker-compose.prod.yml --project-name bot-prod up -d
